services:
  backend:
    build: ./server
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env

  frontend:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - backend
